### PR TITLE
Remove Centos 6 support

### PR DESCRIPTION
**Pull request by TheREK3R**

### CODE REVIEW

**Comment by ramereth** [comment]
@TheREK3R for whatever reason the `server-centos-8` suite is failing for me. My guess isn't related to changes you made but perhaps a change since CentOS 8.3 has been released. Can you look into that and resolve the test? It might need updating.

**Comment by TheREK3R** [comment]
yeah I can do that

**Review by ramereth — APPROVED** [review]

**Comment by ramereth** [comment]
!bump major phpbb,production

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v4.0.0.  Have a nice day!

**Pull request merged**
