### PR TITLE
Move back to percona resources

### PR DESCRIPTION
**Pull request by EMH333**
Sets us up to finally move back to percona resources for all our cookbooks

### CODE REVIEW

**Comment by ramereth** [comment]
@EMH333 will this affect other cookbooks that are still using the other resource?

**Comment by EMH333** [comment]
Our previous move to `mariadb_*` resources will prevent this from having any impact on other cookbooks. This PR updates `percona` so we can migrate to `percona_mysql_*` resources in other cookbooks. This starts the last step on the OSL side of `percona` resource migrations.

**Review by ramereth — APPROVED** [review]
Please do a minor bump.

**Comment by EMH333** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v3.1.0.  Have a nice day!

**Pull request merged**
