### PR TITLE
Update percona to Chef 17-compliant version

### PR DESCRIPTION
**Pull request by detjensrobert**

### CODE REVIEW

**Review by ramereth — APPROVED** [review]
Minor bump

**Comment by detjensrobert** [comment]
!bump mysql ~

**Comment by detjensrobert** [comment]
!bump minor production,phpbb,workstation

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v6.3.0.  Have a nice day!

**Pull request merged**
