### PR TITLE
Add Alma 8 support to mon recipe

### PR DESCRIPTION
**Pull request by EMH333**

### CODE REVIEW

**Comment by ramereth** [comment]
@EMH333 can you please go ahead and remove CentOS Stream in this PR?

**Review by ramereth — APPROVED** [review]
Patch bump

**Comment by EMH333** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v6.8.2.  Have a nice day!

**Pull request merged**
