### PR TITLE
Backup recipes

### PR DESCRIPTION
**Pull request by ramereth**
This includes two recipes:

1. ``xtrabackuprb`` recipe that installs the xtrabackup-rb gem from git which will be used by rdiff-backup
2. A ``backup`` recipe that includes xtrabackup-rb and creates a backup directory at ``/data/backup`` for local daily backups.

### CODE REVIEW

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs ready for your review

**Comment by rettigs** [comment]
Ah, now I see why you wanted the mysqldump version put on hold.

**Comment by ramereth** [comment]
Hmm, I just realized the last commit I pushed was too early. Let me work on fixing that. I should have checked first :(

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs should be good again

**Comment by rettigs** [comment]
What is the purpose of using the xtrabackup-rb wrapper?

**Comment by ramereth** [comment]
@rettigs it provides a nice frontend for managing full/incremental backups using the xtrabackup scripts. Basically adds some logic. The intent is to have rdiff call it directly before running the backup.

**Comment by rettigs** [comment]
:+1:

**Comment by rettigs** [comment]
@ramereth Once this is merged, is it ok to go ahead and replace `mysqldump` with `xtrabackup-rb` in the [rdiff-backup PR](https://github.com/osuosl-cookbooks/rdiff-backup/pull/13) then?

**Comment by ramereth** [comment]
@rettigs no, talk with @jordane about what we're planning on doing.

**Comment by ramereth** [comment]
@jordane any final comments?

**Comment by jordane** [comment]
+1

**Pull request merged**
