### PR TITLE
Add ignore_failure true to git resources

### PR DESCRIPTION
**Pull request by sharoninator**

### CODE REVIEW

**Comment by ramereth** [comment]
LGTM, wait till we can sync to deploy

**Review by ramereth — APPROVED** [review]
Patch bump

**Comment by sharoninator** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v6.9.2.  Have a nice day!

**Pull request merged**
