### PR TITLE
Terminology update

### PR DESCRIPTION
**Pull request by OniLink**
Updated terminology for the MySQL cookbook. Changed 'master' to 'source' and 'slave' to 'replica'. Some uses of old terminology remain, only fixable with an update to MySQL 8 so left those instances alone for now.

### CODE REVIEW

**Comment by ramereth** [comment]
LGTM, hold on merging

**Review by ramereth — APPROVED** [review]
I think this is ready to go with a major bump. Please ping me on slack when you're ready to do this.

**Comment by OniLink** [comment]
!bump major ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v6.0.0.  Have a nice day!

**Pull request merged**
